# Generated by Django 5.1.1 on 2024-09-15 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients.basemodel')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/company')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('clients.basemodel',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients.basemodel')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_phone', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('total_price', models.IntegerField(default=1)),
                ('total_quantity', models.IntegerField(default=1)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('clients.basemodel',),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clients.basemodel')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('invoice_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='download.invoice')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('clients.basemodel',),
        ),
    ]
