# Generated by Django 5.1.1 on 2024-09-15 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='invoice_number',
            new_name='invoice_id',
        ),
    ]
