# Generated by Django 5.1.1 on 2024-09-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_rename_invoice_number_invoiceitem_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
